In [1]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import matplotlib as plt
%matplotlib inline

In [2]:
(x_train, y_train), (x_test,y_test)= keras.datasets.mnist.load_data()

In [3]:
len(x_train)

60000

In [4]:
len(x_test)

10000

In [5]:
x_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [6]:
y_train[0]

5

In [7]:
x_train = x_train/255
x_test = x_test/255

In [8]:
x_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

In [9]:
x_train_flatten =x_train.reshape(len(x_train),28*28)
x_test_flatten = x_test.reshape(len(x_test), 28*28)

In [10]:
x_train_flatten.shape

(60000, 784)

In [11]:
x_test_flatten.shape

(10000, 784)

In [12]:
x_train_flatten[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [13]:
model = keras.Sequential([
    keras.layers.Dense(10, input_shape=(784,), activation='sigmoid')
])
model.compile(optimizer='adam',
             loss ='sparse_categorical_crossentropy',
             metrics = ['accuracy'])
model.fit(x_train_flatten,y_train,epochs=10)



Epoch 1/10


1875/1875 [==============================] - 6s 2ms/step - loss: 0.4760 - accuracy: 0.8752
Epoch 2/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3040 - accuracy: 0.9156
Epoch 3/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2832 - accuracy: 0.9211
Epoch 4/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2727 - accuracy: 0.9234
Epoch 5/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2666 - accuracy: 0.9258
Epoch 6/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2619 - accuracy: 0.9277
Epoch 7/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2583 - accuracy: 0.9278
Epoch 8/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2555 - accuracy: 0.9286
Epoch 9/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2529 - accuracy: 0.9301
Epoch 10/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0

In [14]:
model.evaluate(x_test_flatten,y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.2666 - accuracy: 0.9261


[0.26663121581077576, 0.9261000156402588]

In [15]:
y_predict = model.predict(x_test_flatten)

313/313 [==============================] - 1s 2ms/step


In [16]:
y_predict[0]

array([3.2976323e-03, 2.1417783e-08, 2.3775335e-02, 9.6062648e-01,
       9.2015538e-04, 1.7906845e-01, 3.2661958e-08, 9.9985272e-01,
       8.1591427e-02, 7.2879243e-01], dtype=float32)

In [17]:
model.evaluate(x_train_flatten,y_train)

1875/1875 [==============================] - 5s 2ms/step - loss: 0.2452 - accuracy: 0.9321


[0.24523459374904633, 0.9320666790008545]

In [19]:
np.argmax(y_predict[0])

7

In [20]:
#USING HIDDEN LAYER

In [21]:
model=keras.Sequential([
    keras.layers.Dense(100,input_shape=(784,), activation = 'relu')
])
model.compile(optimizer='adam',
             loss = 'sparse_categorical_crossentropy',
             metrics =['accuracy'])
model.fit(x_train_flatten,y_train,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 8s 4ms/step - loss: 4.1391 - accuracy: 0.1931
Epoch 2/10
1875/1875 [==============================] - 6s 3ms/step - loss: 4.2938 - accuracy: 0.1448
Epoch 3/10
1875/1875 [==============================] - 6s 3ms/step - loss: 4.2073 - accuracy: 0.1621
Epoch 4/10
1875/1875 [==============================] - 7s 4ms/step - loss: 4.3024 - accuracy: 0.1318
Epoch 5/10
1875/1875 [==============================] - 6s 3ms/step - loss: 4.2641 - accuracy: 0.1482
Epoch 6/10
1875/1875 [==============================] - 7s 4ms/step - loss: 4.2060 - accuracy: 0.1582
Epoch 7/10
1875/1875 [==============================] - 7s 4ms/step - loss: 4.1146 - accuracy: 0.1559
Epoch 8/10
1875/1875 [==============================] - 6s 3ms/step - loss: 3.9756 - accuracy: 0.1719
Epoch 9/10
1875/1875 [==============================] - 7s 4ms/step - loss: 4.0231 - accuracy: 0.1664
Epoch 10/10
1875/1875 [==============================] - 7s 4ms/step - loss: 3.895

In [22]:
model.evaluate(x_test_flatten, y_test)


313/313 [==============================] - 1s 3ms/step - loss: 3.9137 - accuracy: 0.1952


[3.9136812686920166, 0.19519999623298645]

In [23]:
y_predicted = model.predict(x_test_flatten)
y_predicted[0]

313/313 [==============================] - 1s 2ms/step


array([0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 1.5417947, 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.       , 0.       , 0.       , 

In [25]:
#USING FLATTEN LAYER SO THAT WEDONT HAVE TO CALL RESHAPE ON INPUT DATASET

In [26]:
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28,28)),
    keras.layers.Dense(100, activation='relu'),
    keras.layers.Dense(100, activation='sigmoid'),
])

In [27]:
model.compile(optimizer='adam',
             loss = 'sparse_categorical_crossentropy',
             metrics =['accuracy'])
model.fit(x_train,y_train,epochs=10)

Epoch 1/10
1875/1875 [==============================] - 8s 4ms/step - loss: 0.3312 - accuracy: 0.9094
Epoch 2/10
1875/1875 [==============================] - 7s 3ms/step - loss: 0.1412 - accuracy: 0.9583
Epoch 3/10
1875/1875 [==============================] - 7s 3ms/step - loss: 0.0991 - accuracy: 0.9707
Epoch 4/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0764 - accuracy: 0.9771
Epoch 5/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0594 - accuracy: 0.9816
Epoch 6/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0484 - accuracy: 0.9855
Epoch 7/10
1875/1875 [==============================] - 7s 3ms/step - loss: 0.0402 - accuracy: 0.9874
Epoch 8/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0332 - accuracy: 0.9898
Epoch 9/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0277 - accuracy: 0.9913
Epoch 10/10
1875/1875 [==============================] - 7s 4ms/step - loss: 0.022

In [28]:
model.evaluate(x_test,y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0858 - accuracy: 0.9755


[0.08576451241970062, 0.9754999876022339]